//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guia
    {
        public Guia()
        {
            this.Guia_Detalle = new HashSet<Guia_Detalle>();
        }
    
        public int IdGuia { get; set; }
        public int IdLocal { get; set; }
        public System.DateTime Fachasalida { get; set; }
        public string Transportista { get; set; }
    
        public virtual Local Local { get; set; }
        public virtual ICollection<Guia_Detalle> Guia_Detalle { get; set; }
    }
}
