//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Detalle
    {
        public int IdOrden { get; set; }
        public int IdProducto { get; set; }
        public decimal PrecioCompra { get; set; }
        public int CantidadSolicitada { get; set; }
        public int CantidadRecibida { get; set; }
        public string Estado { get; set; }
    
        public virtual Orden Orden { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
