//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Guia_Detalle = new HashSet<Guia_Detalle>();
            this.Orden_Detalle = new HashSet<Orden_Detalle>();
        }
    
        public int IdProducto { get; set; }
        public int IdCategoria { get; set; }
        public int IdProveedor { get; set; }
        public string Nombre { get; set; }
        public string UnidadMedida { get; set; }
        public decimal PrecioProveedor { get; set; }
        public int StockActual { get; set; }
        public int StockMinimo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Guia_Detalle> Guia_Detalle { get; set; }
        public virtual ICollection<Orden_Detalle> Orden_Detalle { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
