//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int IdProveedor { get; set; }
        public string Nombre { get; set; }
        public string Representante { get; set; }
        public string Dirección { get; set; }
        public string Ciudad { get; set; }
        public int Cedula { get; set; }
        public int Telefono { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
